AnswerSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("user.urls",namespace="user")),
    path('', include("subject.urls",namespace="subject")),
]

apps/subject/urls.py
from django.urls import path, re_path
from subject import views

app_name = "subject"

urlpatterns = [
    path('', views.IndexView.as_view(),name="index"),
    path('answer', views.DetailView.as_view()), # 答案提交
    re_path(r'^sub/(\d+)$', views.DetailView.as_view()), # 分组（）
]

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>请回答</title>
</head>
<body>
<h1>{{ type_obj.type }}题目如下:</h1>
   {% if request.user.is_authenticated %}
        欢迎您：<strong>{{ request.user.username }}</strong>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/user/logout">注销</a>
    {% else %}
        <a href="/user/login">登录</a>&nbsp;&nbsp;&nbsp;<a href="/user/register">注册</a>
    {% endif %}<br><br>
题目如下：<br>
<ul>
    <form method="post" action="/answer">{% csrf_token %}
        <input type="hidden" name="type_id" value={{ type_id }}>
        <ul>
            {% for sub,sub_options in dict.items %}
                {% if sub.sub_type %}
                    <p><li>{{ sub.sub }}(多选){{ sub.sub_score }}分</li></p>
                        {% for sub_option in sub_options %}
        {#                        <p>{{ sub_option.option }}<input type="checkbox" name={{ sub.sub }} value={{ sub_option.option }}></p>#}
                            {{ sub_option.option }}<input type="checkbox" name={{ sub.sub }} value={{ sub_option.option }}>
                        {% endfor %}
                {% else %}
                    <p><li>{{ sub.sub }}(单选){{ sub.sub_score }}分</li></p>
                        {% for sub_option in sub_options %}
                            {{ sub_option.option }}<input type="radio" name={{ sub.sub }} value={{ sub_option.option }}>
                        {% endfor %}
                {% endif %}
            {% endfor %}
        </ul><br><br>
        <input type="submit" id="lan" value="提交答案">
    </form><br><br>
    {{ msg }}
<h3><a href={% url "subject:index" %}>回到首页继续答题</a></h3>
</ul>
<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js">
</script>
<script>
$(document).ready(function(){
  $("#lan").click(function(){
    $("#lan").hide();
  });
});
</script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>答题系统</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        欢迎您：<strong>{{ request.user.username }}</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/user/logout">注销</a>
    {% else %}
        <a href="/user/login">登录</a>&nbsp;&nbsp;&nbsp;<a href="/user/register">注册</a>
    {% endif %}
<ul><br>
    <p>答题排行榜：</p>
    {% for user in users %}
       <li>{{ user }}({{ user.score }})</li>
    {% endfor %}
</ul>
<ul>
    {% for type in types %}
       <li><a href="/sub/{{ type.id }}">{{ type.type }}</a></li>
    {% endfor %}
</ul>

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>用户登录</title>
    <link rel="stylesheet" href="{% static 'plugin/layui/css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/mobile.css' %}">
</head>
<body>
<div class="login-bg subject-color layui-row"></div>
<form action="" method="post">{% csrf_token %}
    <div class="login-box">

        <div class="login-form">
            <p>用户名：</p>
            <input type="text" name="username" placeholder="登录用户名" class="layui-input">
        </div>

        <div class="login-form">
            <input type="password" name="password" placeholder="请输入密码" class="layui-input">
        </div>


        <div class="login-form">
            <button class="layui-btn layui-btn-fluid layui-btn-normal ">登录</button>
        </div><br>
        <div class="login-form">
            <a href="/user/register" class="layui-btn layui-btn-fluid">注册</a>
        </div><br>
        {{ errmsg }}
    </div>
</form>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>用户注册</title>
    <link rel="stylesheet" href="{% static 'plugin/layui/css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/mobile.css' %}">
</head>
<body>
<div class="login-bg subject-color layui-row"></div>
<div class="login-box">
    <div class="login-title layui-row">
        <h2>注册</h2>
    </div>
    <p class="login-form">
            <a href="/user/login" ><strong>已有帐号？点击登录</strong></a>
    </p><br>
    <div class="hr-line-div"></div>
    <form action="" method="post">{% csrf_token %}
        <div class="login-form">
            <p>用户名：</p>
            <div class="layui-row row-align">
                <div class="valicode-box" style="width: 60%;">
                    <input type="text" name="username" placeholder="请输入用户名" class="layui-input">
                </div>
            </div>
        </div>

        <div class="login-form">
            <p>手机号码：</p>
            <div class="layui-row row-align">
                <div class="valicode-box" style="width: 60%;">
                    <input type="text" name="mobile" placeholder="请输入手机号" class="layui-input">
                </div>
            </div>
        </div>

        <div class="login-form">
            <p>密码：</p>
            <input type="password" name="password" placeholder="至少八位，必须包含大小写字母及数字" class="layui-input">
        </div>
        <div class="login-form">
            <p>确认密码：</p>
            <input type="password" name='cpassword' placeholder="请再次输入密码" class="layui-input">
        </div>

        <div class="login-form">
            <button class="layui-btn layui-btn-fluid">立即注册</button>
        </div>
    </form><br>
    {{ errmsg }}
</div>
</body>
</html>